apiVersion: v1
kind: Pod 
metadata:
  name: kubia-manual
  namespace: default
  labels:
    app: kubia
spec:
  containers:
    - image: nginx
      name:  nginx
      ports:
      - containerPort: 8080
        protocol: TCP
